"""
Nigerian Names Database for PII Detection.

Contains ~2000 common Nigerian names from major ethnic groups:
- Yoruba (~700 names)
- Hausa (~500 names)
- Igbo (~500 names)
- Other ethnic groups (~300 names): Efik, Ibibio, Tiv, Ijaw, Edo, Urhobo, etc.

Stored as a frozenset for O(1) lookup and immutability.
All names are lowercase for case-insensitive matching.

Note: This list includes both first names and surnames commonly used in Nigeria.
"""

# Common words that may match names but are used in everyday context
# These should NOT be redacted when used as common words
COMMON_WORD_EXCLUSIONS = frozenset({
    # Virtue/religious names often used as common words
    "hope", "grace", "blessing", "faith", "patience",
    "joy", "mercy", "goodness", "peace", "love",
    "gift", "precious", "divine", "glory", "victory",
    "comfort", "favour", "favor", "promise", "wisdom",
    "prosper", "success", "happy", "bright", "light",
    "angel", "saint", "praise", "worship", "gospel",
    "heaven", "glory", "honour", "honor", "truth",
    "progress", "increase", "wealth", "king", "queen",
    "prince", "princess", "lord", "saviour", "savior",
    # Common English words that might match
    "will", "may", "peter", "john", "james", "paul",
    "rose", "lily", "ivy", "pearl", "ruby", "diamond",
    # Common prepositions/words that could be captured by phrase patterns
    "at", "on", "in", "to", "by", "for", "from", "with",
    "about", "after", "before", "here", "there", "now",
    "soon", "later", "today", "tomorrow", "please", "thanks",
    # Days of the week (some are Nigerian names too)
    "sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday",
    # Common English words that are also Nigerian names
    "victor", "adam", "wilson", "christian", "junior", "senior",
    "baba", "mama", "papa", "chief", "amen",
})

# Nigerian names organized by ethnic group
# All stored lowercase for case-insensitive matching
NIGERIAN_NAMES_SET = frozenset({
    # ==========================================
    # YORUBA NAMES (~700)
    # ==========================================

    # Male Yoruba Names
    "adebayo", "oluwaseun", "oluwafemi", "ayomide", "temitope",
    "adewale", "olumide", "babatunde", "oladipo", "oluwole",
    "adeniyi", "adekunle", "adetola", "adetokunbo", "adeyemi",
    "akintunde", "akinwale", "akinwumi", "akinola", "akintoye",
    "babajide", "babafemi", "babalola", "bamidele", "bankole",
    "boluwatife", "damilare", "damilola", "emmanuel", "femi",
    "folarin", "gbenga", "gboyega", "idowu", "ifeoluwa",
    "ifeanyi", "jide", "kayode", "kehinde", "kolawole",
    "kunle", "lateef", "lekan", "mayowa", "muyiwa",
    "niyi", "oba", "obafemi", "obi", "odunayo",
    "ogunleye", "ogunwale", "ojo", "oladele", "oladimeji",
    "olalekan", "olamide", "olanrewaju", "olasunkanmi", "olatunde",
    "olawale", "olayinka", "olufemi", "olumuyiwa", "olusegun",
    "olusola", "oluwadarasimi", "oluwadamilare", "oluwadamilola", "oluwaferanmi",
    "oluwafunmilayo", "oluwagbemiga", "oluwakorede", "oluwanifemi", "oluwaseyi",
    "oluwashina", "oluwatobi", "oluwatosin", "oluwatobiloba", "oluwatomisin",
    "oluwatunmise", "omololu", "omoniyi", "opeyemi", "oreoluwa",
    "oyedeji", "oyewole", "rotimi", "segun", "seyi",
    "shola", "sola", "sunday", "taiwo", "tayo",
    "temiloluwa", "temilade", "temidayo", "tobiloba", "tobi",
    "tolu", "tolulope", "tomide", "tomisin", "tunde",
    "wale", "wasiu", "wole", "yemi", "yinka",
    "yusuf", "zainab", "abdul", "abdulrahman", "abdulkadir",

    # Female Yoruba Names
    "abimbola", "abosede", "adaeze", "adanna", "adenike",
    "adesewa", "aduke", "ajoke", "akanke", "akinyi",
    "alaba", "anuoluwapo", "arike", "ayodele", "ayoola",
    "bisoye", "bisola", "bimpe", "bolaji", "bose",
    "bosede", "bukola", "bunmi", "damilola", "deborah",
    "dorcas", "ebunoluwa", "enitan", "esther", "eunice",
    "fadekemi", "folake", "folasade", "folashade", "foluke",
    "funke", "funmilayo", "gbemisola", "ife", "ifeoma",
    "iretioluwa", "joke", "jumoke", "kehinde", "kemi",
    "kikelomo", "kofoworola", "lara", "lola", "mary",
    "modupe", "mojisola", "monisola", "mosunmola", "motunrayo",
    "nike", "nimota", "olabisi", "oladunni", "olaide",
    "omolara", "omolola", "omolade", "omowunmi", "oni",
    "opeyemi", "oreoluwa", "oyinkansola", "peju", "remi",
    "ronke", "shade", "sade", "simisola", "simi",
    "sinmisola", "sola", "solape", "taiwo", "temilade",
    "temitayo", "temitope", "tinuade", "tinuola", "titilayo",
    "titilope", "tolu", "tolulope", "tosin", "toyosi",
    "wunmi", "yemisi", "yetunde", "yewande", "yinka",

    # Yoruba Surnames
    "abiodun", "abiola", "adebisi", "adegoke", "adejumo",
    "adelaja", "adeleke", "adeleye", "ademola", "adeniji",
    "adeniran", "adeola", "aderemi", "adesanya", "adesina",
    "adetayo", "adewunmi", "adeyanju", "adeyeye", "adeyinka",
    "afolabi", "afolayan", "agbaje", "ajayi", "ajibade",
    "ajibola", "ajiboye", "akande", "akanmu", "akanni",
    "akerele", "akin", "akindele", "akingbade", "akinlade",
    "akinloye", "akinpelu", "akinremi", "akinsanya", "akinsola",
    "akintola", "akinyele", "akinyemi", "akinwunmi", "alabi",
    "alao", "amoo", "anifowose", "animashaun", "aremu",
    "asaolu", "ashiru", "awodele", "awolaja", "awolowo",
    "ayandele", "ayanlaja", "ayeni", "ayoade", "babalola",
    "bada", "bademosi", "badmus", "balogun", "daramola",
    "disu", "dosunmu", "eguae", "egunjobi", "elegbede",
    "fabiyi", "fadahunsi", "fagbemi", "fagbohun", "fagunwa",
    "fakoya", "falana", "famuyide", "fasanya", "fashola",
    "fatai", "fayemi", "fayose", "folorunso", "ganiyu",
    "idowu", "ilesanmi", "jaiyeola", "jimoh", "kareem",
    "kolade", "kolawole", "lamidi", "lasisi", "mustapha",
    "odeyemi", "odugbemi", "odunsi", "odusanya", "odusote",
    "oduya", "ogbechie", "ogunbiyi", "ogundele", "ogundipe",
    "ogunjobi", "ogunlana", "ogunleye", "ogunmodede", "ogunsanya",
    "ogunyemi", "ojediran", "ojelabi", "ojetunde", "ojikutu",
    "ojuolape", "okafor", "okeowo", "okonkwo", "okunola",
    "oladapo", "oladele", "oladipo", "oladunjoye", "olagunju",
    "olajide", "olajuwon", "olaleye", "olanipekun", "olaniran",
    "olanlokun", "olanrewaju", "olaoye", "olasupo", "olatunji",
    "olawuyi", "olayemi", "olayiwola", "olofinbiyi", "ologun",
    "olokode", "olopade", "olowookere", "oloyede", "olu",
    "olubunmi", "olufunke", "olugbenga", "olurin", "olusanya",
    "olusola", "oluwafemi", "oluwole", "omidiran", "omisore",
    "omodara", "omojola", "omole", "omololu", "omoniyi",
    "onabanjo", "onafuwa", "onagoruwa", "onasanya", "oni",
    "onifade", "onwueme", "onyeka", "osho", "osinbajo",
    "osuntokun", "otedola", "owolabi", "owolawi", "owonikoko",
    "oyebanji", "oyebode", "oyedele", "oyedepo", "oyediran",
    "oyegoke", "oyekan", "oyekunle", "oyewo", "oyewole",
    "oyeyemi", "oyinlola", "salami", "salawu", "salam",
    "sanusi", "shodipo", "shonibare", "shonubi", "shopeju",
    "solanke", "solarin", "soyinka", "taiwo", "tijani",
    "tinubu", "yusuf",

    # ==========================================
    # HAUSA NAMES (~500)
    # ==========================================

    # Male Hausa Names
    "abubakar", "abdullahi", "abdulrahman", "abdulkadir", "abdulmalik",
    "abdulsalam", "abdulwahab", "abdulaziz", "abdulmajid", "abdulhamid",
    "adam", "adamu", "ahmad", "ahmed", "aliyu",
    "aminu", "amadu", "audu", "auwal", "baba",
    "babangida", "balarabe", "bala", "bello", "buhari",
    "dalhatu", "danjuma", "danmusa", "dantata", "dauda",
    "dikko", "dodo", "garba", "gidado", "gwadabe",
    "hamidu", "hamza", "haruna", "hassan", "hussaini",
    "ibrahim", "idris", "isa", "isah", "ismail",
    "isyaku", "jafaru", "jibril", "jibrin", "kabiru",
    "kadiri", "kamaludeen", "kankara", "lawal", "lawali",
    "liman", "maccido", "magaji", "maigari", "mainasara",
    "maitama", "maje", "malam", "mamman", "mani",
    "mansur", "masud", "modu", "mohammed", "muhammadu",
    "murtala", "musa", "nasiru", "nuhu", "nura",
    "rilwanu", "rimi", "sabo", "sadiq", "sahabi",
    "saidu", "salihu", "salisu", "sambo", "sanusi",
    "shagari", "shamsuddeen", "shehu", "shuaibu", "sule",
    "suleman", "suleiman", "tanko", "tijjani", "umar",
    "umaru", "usman", "wada", "yakubu", "yaro",
    "yahuza", "yau", "yunusa", "yusuf", "zakariya",
    "zaki", "zubairu",

    # Female Hausa Names
    "aisha", "aishatu", "amina", "aminat", "asabe",
    "binta", "bilkisu", "dije", "faiza", "falmata",
    "fati", "fatima", "fatimah", "hadiza", "hafsat",
    "hajara", "halima", "halimat", "halimatu", "hauwa",
    "hawwa", "hindatu", "hussaina", "jamila", "jummai",
    "kande", "khadija", "khadijat", "kulthum", "ladidi",
    "laraba", "maimuna", "maimunat", "maryam", "murja",
    "nafisa", "nafisat", "rahama", "rahila", "rabi",
    "rakiya", "rashida", "safiya", "safiyya", "sahura",
    "saida", "saidatu", "sakina", "salamatu", "salma",
    "saratu", "shamsiyya", "suwaiba", "talatu", "uwani",
    "walida", "yagana", "yamuna", "yasmin", "zainab",
    "zainabou", "zarah", "zuwaira",

    # Hausa Surnames / Family Names
    "abubakar", "adamu", "ahmad", "aliyu", "bello",
    "buhari", "danjuma", "dikko", "garba", "gusau",
    "gwandu", "idris", "jega", "kano", "katagum",
    "katsina", "kebbi", "lawal", "maiduguri", "maitama",
    "makama", "muhammed", "ringim", "sambo", "sanusi",
    "shehu", "sokoto", "suleiman", "turaki", "waziri",
    "yar'adua", "yaradua", "zaria", "zazzau",

    # ==========================================
    # IGBO NAMES (~500)
    # ==========================================

    # Male Igbo Names
    "adaeze", "ahamefula", "akachukwu", "akachi", "akunna",
    "amarachi", "amara", "azubuike", "chidi", "chidiebere",
    "chidiogo", "chidozie", "chiemeka", "chiemerie", "chigbo",
    "chigozie", "chika", "chike", "chikelu", "chikezie",
    "chimdi", "chinaemerem", "chinagorom", "chinasa", "chinedu",
    "chinelo", "chinemerem", "chineye", "chinonso", "chinua",
    "chinweike", "chinwendu", "chinwuba", "chisom", "chisomaga",
    "chuks", "chukwubuikem", "chukwuebuka", "chukwudi", "chukwuemeka",
    "chukwuka", "chukwuma", "chukwunonso", "chukwunyere", "cyprian",
    "dike", "dozie", "dubem", "ebere", "ebube",
    "echezona", "ejike", "ekene", "ekwueme", "elochukwu",
    "emeka", "emezue", "enyinnaya", "ezechukwu", "ezeji",
    "ezenwa", "ezenwanyi", "ezeofor", "ezeudo", "festus",
    "hyacinth", "ifeanyichukwu", "ifeanyi", "ifechi", "ifeoma",
    "igwe", "iheanyi", "ihejirika", "ikechukwu", "ikedi",
    "ikemefuna", "ikenna", "ikenga", "innocent", "izuchukwu",
    "jideofor", "jude", "kalu", "kelechi", "kenechukwu",
    "kingsley", "kosisochukwu", "lotanna", "maduka", "mazi",
    "mmaduabuchi", "mmaduka", "mmesoma", "munachi", "munachimso",
    "ndubuisi", "ndubueze", "nduka", "ndukwe", "ngozi",
    "nkemdirim", "nkem", "nkemjika", "nnabuike", "nnaemeka",
    "nnaji", "nnamdi", "nnaoma", "nonso", "nwachukwu",
    "nwafor", "nwankwo", "nwabueze", "nwachinemere", "nwadike",
    "nwaeze", "nwagbara", "nwankpa", "nwaobi", "nwaogu",
    "nwaoha", "nwaokolo", "obiajulu", "obialunamma", "obianna",
    "obidi", "obiekwe", "obierika", "obinna", "obinwanne",
    "obi", "obiora", "obiozor", "obodo", "obumselu",
    "odera", "odili", "odogwu", "odumegwu", "ofili",
    "ofoegbu", "ofor", "ogbonnaya", "ogochukwu", "oguguo",
    "oguike", "ohaji", "ojukwu", "okechukwu", "okeke",
    "okemiri", "okezie", "okoro", "okonkwo", "okorie",
    "okpala", "okwu", "okwudili", "okwuosa", "olisaemeka",
    "olisaeloka", "oliseh", "oluchukwu", "olumba", "oluomachi",
    "omenka", "omeoga", "onyebuchi", "onyeka", "onyekachi",
    "onyekwelu", "onyema", "onyemaechi", "onyenwenu", "orji",
    "osondu", "osuji", "osita", "ozioma", "paschal",
    "sylvester", "tochukwu", "tobechukwu", "tobechi", "uche",
    "uchechukwu", "uchenna", "udochukwu", "udoka", "udu",
    "ugochukwu", "ugonna", "ugwu", "ujunwa", "ukaegbu",
    "ukpabi", "uzochukwu", "uzodinma", "uzoma", "victor",
    "vitalis", "wilson", "zubby", "zik",

    # Female Igbo Names
    "adaeze", "adaora", "adanna", "adaobi", "adaugo",
    "adaure", "akudo", "amaka", "amarachi", "amara",
    "chiamaka", "chibuzo", "chidimma", "chidinma", "chidubem",
    "chigozirim", "chimamanda", "chimdindu", "chimere", "chinyelu",
    "chisom", "ebele", "ezinne", "ginika", "ginikanwa",
    "ifeoma", "ifunanya", "ijeoma", "ijenwanyi", "kamsiyochukwu",
    "kosarachi", "lotachukwu", "maryanne", "munachimso", "ngozichukwu",
    "nkechi", "nkechinyere", "nkiru", "nkiruka", "nmesoma",
    "nneka", "nnenna", "nnenne", "nneoma", "nwando",
    "obianuju", "obiageli", "obianauju", "odichi", "ogochukwu",
    "ogoamaka", "oluchi", "oluchukwu", "oluebubechi", "olunwa",
    "onyinye", "onyinyechukwu", "sopuruchi", "somtochi", "tobechukwu",
    "tochukwu", "uchechukwu", "uchenna", "ugochi", "uloma",
    "uzoamaka", "uju", "ujunwa", "yagazie", "zara",

    # Igbo Surnames
    "achebe", "adigwe", "agbakoba", "agbasi", "aguiyi",
    "aham", "ajaero", "ajie", "akagha", "akajiugo",
    "akunne", "akunyili", "aluko", "amadi", "amaechi",
    "amakiri", "anambra", "anekwe", "ani", "aniekwe",
    "aniekan", "anigbo", "anikwe", "anih", "anionwu",
    "anoke", "anyanwu", "arazu", "asogwa", "awa",
    "azikiwe", "azubuike", "azuka", "dim", "dimgba",
    "duru", "ebigbo", "egwu", "ejiofor", "ejindu",
    "ekweonu", "ekwueme", "eluwa", "emedolu", "emejulu",
    "emeka", "emenike", "emenuga", "enugu", "erondu",
    "eze", "ezeagu", "ezeani", "ezeanya", "ezediaro",
    "ezeh", "ezeibekwe", "ezeife", "ezekiel", "ezekwesili",
    "ezema", "ezemadu", "ezemonye", "ezenwanyi", "ezeoba",
    "ezeokoli", "ezeudu", "ezinwa", "ezirim", "ezugwu",
    "gbulie", "ibeh", "idigo", "igbokwe", "igwe",
    "igwilo", "ihenacho", "ijomah", "ikedife", "ikeh",
    "ikemba", "ilogu", "imo", "ironsi", "iwuagwu",
    "kalu", "madike", "madubuko", "mbachu", "mbagwu",
    "mbakwe", "mbanaso", "mbaonu", "mbonu", "mezu",
    "mgbemena", "ndigwe", "nduka", "ndukauba", "ndulue",
    "ngige", "nkwocha", "nnadozie", "nnadi", "nnamchi",
    "nnamdi", "nnanna", "nnorom", "nwabueze", "nwachuku",
    "nwachukwu", "nwadiala", "nwagbo", "nwagbara", "nwaigwe",
    "nwaka", "nwakeze", "nwakor", "nwala", "nwamarah",
    "nwanna", "nwanodi", "nwaogu", "nwaoha", "nwaorgu",
    "nwaubani", "nweke", "nwigwe", "nwobi", "nwobodo",
    "nwodo", "nwokedi", "nwokedike", "nwokeke", "nwokobia",
    "nwokocha", "nwokolo", "nwokoye", "nwoko", "nwosu",
    "nwoye", "nzegwu", "nzekwe", "nzelu", "obiagwu",
    "obiechina", "obiekwe", "obikezie", "obi", "obiora",
    "obioha", "obiozo", "obuasi", "odili", "odoemena",
    "odumegwu", "offor", "ofili", "ogbonna", "ogbuagu",
    "ogugua", "oguike", "oguine", "ohanaeze", "ojiakor",
    "ojike", "ojukwu", "okafor", "okagbue", "okala",
    "okechukwu", "okeke", "okemiri", "okere", "okigbo",
    "okito", "okoh", "okolo", "okonkwo", "okorie",
    "okoroafor", "okoye", "okpala", "okparaeke", "okudo",
    "okwara", "okwudishu", "okwuosa", "olise", "olu",
    "omeje", "omenigbo", "onuigbo", "onuoha", "onwuachi",
    "onwuamaegbu", "onwudiwe", "onwuka", "onwukwe", "onwurah",
    "onyeachonam", "onyeagba", "onyeakagbu", "onyeanu", "onyechi",
    "onyejiaka", "onyekwere", "onyekwelu", "onyema", "onyeneke",
    "onyenucheya", "onyido", "opara", "orah", "oranu",
    "orji", "osagie", "osigwe", "osuagwu", "osueke",
    "osuji", "ottah", "otuka", "owoh", "ubaka",
    "uche", "uchechi", "uchem", "uchenna", "udeh",
    "udemba", "udeozo", "udo", "udoji", "udokwu",
    "udoye", "ugochukwu", "ugo", "ugonma", "ugwoke",
    "ugwu", "ugwuanyi", "ugwueze", "ukachukwu", "ukah",
    "ukanwa", "ukeje", "ukpabi", "ukpaka", "umeh",
    "unachukwu", "unaegbu", "uwaezuoke", "uwaoma", "uyanwune",
    "uzo", "uzochukwu", "uzodinma", "uzodimma", "uzoma",
    "uzomah", "uzor", "wabara", "zebrudaya", "zik",

    # ==========================================
    # OTHER ETHNIC GROUP NAMES (~300)
    # ==========================================

    # Efik / Ibibio / Annang Names (Cross River / Akwa Ibom)
    "abasiekong", "abasifreke", "abasi", "abasiono", "abasitari",
    "abiodun", "adiaha", "akon", "akpabio", "akpan",
    "akpaninyene", "akpanobong", "akwaowo", "aniefiok", "anietie",
    "aniette", "anyanime", "arit", "asukwo", "atim",
    "bassey", "edidem", "edidiong", "edima", "edo",
    "effiom", "effiong", "ekom", "ekong", "ekpenyong",
    "ekpo", "ekwere", "ema", "emem", "emembong",
    "enobong", "eno", "esien", "essien", "essiet",
    "etim", "etok", "ette", "ettim", "etukudo",
    "eyo", "idara", "ifiok", "imaobong", "ime",
    "inem", "inibehe", "iniobong", "inyang", "inyene",
    "isong", "ita", "itoro", "mbong", "mkpong",
    "mma", "mmanyam", "mmeyen", "ndifreke", "ndiok",
    "nkoyo", "nsidibe", "nsikak", "ntiedo", "ntuen",
    "nyanaso", "nyong", "obong", "obot", "odiong",
    "offiong", "ofon", "okon", "okoro", "okpoyo",
    "okuku", "onofiok", "orok", "oto", "owoidighe",
    "owoicho", "ubong", "udeme", "udoh", "udom",
    "udo", "uduak", "ufot", "ukeme", "ukpong",
    "umana", "umobong", "unwana", "uyai", "uyo",

    # Edo / Bini Names
    "aigbe", "aghahowa", "aimuamwosa", "aigbogun", "airhuenmwosa",
    "akenzua", "eghosa", "ehigiator", "ehioze", "ehimare",
    "ehinomen", "ehizogie", "ejiro", "erediauwa", "ero",
    "esosa", "esohe", "eweka", "idemudia", "ighile",
    "igho", "iguodala", "imade", "iro", "ivie",
    "iwu", "obahiagbon", "oba", "obasohan", "obayagbona",
    "obehi", "odion", "ofure", "ogan", "oghenetega",
    "oghogho", "ogiamen", "ogiefo", "ogiemudia", "omoregie",
    "omorogbe", "omoruyi", "osagie", "osaretin", "osaro",
    "osayande", "osayomwanbo", "osazee", "osazuwa", "osayuki",
    "oseghale", "osemwengie", "osemudiamen", "oserheimen", "osunde",
    "otaigbe", "owie", "uwagboe", "uwaila", "uwaifo",
    "uwuigbe", "uyi", "uyilawa", "uyiosa", "vero",

    # Ijaw Names (Delta / Bayelsa)
    "agbani", "alagoa", "alamieyeseigha", "amaebi", "amakoromo",
    "amangala", "asara", "azaiki", "beke", "bibowei",
    "daukoru", "dickson", "diete", "diri", "dokubo",
    "ebiere", "ebiowei", "egberipou", "egbesu", "ekine",
    "ekio", "ekpein", "emelah", "eperikumo", "ere",
    "ereyitomi", "etifa", "ezekiel", "fernandez", "gnekede",
    "igali", "ijaw", "iposi", "isokariari", "izon",
    "jephthah", "jumbo", "kalabari", "kalio", "kiagbodo",
    "koluama", "manson", "obuoforibo", "obuzor", "okoko",
    "okotobo", "ombo", "opuada", "opuene", "oronto",
    "oweipa", "oyeinka", "perekeme", "pere", "peretomode",
    "piniki", "porter", "seiyefa", "sese", "sikpi",
    "spiff", "tari", "tariela", "tarila", "terngu",
    "timipre", "tompolo", "toruyowei", "toru", "tubonemi",
    "tuodolo", "wariboko", "warri", "woyengikuro",

    # Urhobo Names (Delta)
    "akpojotor", "akpobome", "akporotu", "akpoveta", "atake",
    "avwenagha", "ejiro", "ejiroghene", "emakpor", "emamoke",
    "erhinyoja", "erivwo", "ese", "etega", "evwaraye",
    "ighofose", "isoje", "jemide", "kesiena", "kevwe",
    "mariorigha", "obaro", "oboro", "oghenekaro", "oghenekevwe",
    "ogheneochuko", "oghenemaro", "oghenevwede", "oghenovo", "oghosa",
    "ohwofasa", "ojakovo", "okiemute", "okotie", "okpe",
    "okpobiri", "okporua", "olorogun", "olomu", "omamuyovwi",
    "omatseye", "omene", "omoraka", "omorodion", "omoroghomwan",
    "omovie", "onajite", "onocha", "onose", "onovughakpo",
    "onovo", "orefe", "oseji", "oteri", "otega",
    "ovie", "owhe", "owhonda", "oyovwi", "ozerua",
    "ozoro", "reyere", "rorome", "rukevwe", "rukewe",
    "tetsola", "timibi", "toritseju", "toviebi", "uduehi",
    "uduefe", "ughere", "ukpokpo", "uvie", "uyoyou",

    # Tiv Names (Benue)
    "aboho", "abugh", "adoo", "agada", "agber",
    "ahemba", "akiga", "akile", "akpa", "akpe",
    "akpenpuun", "akpera", "akulga", "alu", "amande",
    "ander", "andzua", "anongo", "anyam", "aondo",
    "atim", "atom", "atsaka", "atsua", "aver",
    "awuhe", "ayaaga", "ayongo", "dajoh", "dondo",
    "dooga", "dzuamo", "dzua", "erdoo", "erkima",
    "gbenyi", "gbo", "gboko", "hemba", "hyacinth",
    "ianna", "idiongo", "ieren", "ihagh", "ikyor",
    "ingyoroko", "iorliam", "ityavyar", "ivande", "jato",
    "jimin", "kajo", "kange", "kaura", "kente",
    "kimbir", "kpamber", "kpamor", "kumga", "kurgwa",
    "kwaghtaver", "malu", "mbahemen", "mbakurunga", "mbanengen",
    "mbatsav", "mbatyough", "mbaveren", "mbavihi", "mkem",
    "mnenge", "msaaku", "msenda", "msugh", "nyam",
    "nyiev", "nyitse", "nyiyongo", "ocholi", "ode",
    "oija", "okoh", "orkuma", "ortese", "oryina",
    "pever", "pine", "sesugh", "shagba", "shagbaor",
    "shaminja", "shenge", "shija", "shikaan", "shior",
    "suswam", "swem", "takan", "tar", "tarka",
    "tarzoor", "ter", "terfa", "terhemen", "terkaa",
    "terkimbi", "terkula", "tertsegha", "terseer", "terzungwe",
    "tiv", "tor", "torkuma", "torkwase", "tsavsar",
    "tsegba", "tsekura", "tsenongu", "tsevende", "tyokyaa",
    "tyoshar", "ugba", "ugemba", "ukuma", "ushongo",
    "uza", "vandeikya", "verem", "wai", "wanger",
    "wuese", "yaga", "yakobu", "yange", "yankyaa",
    "yaomun", "yav", "yua", "yue", "zahemen",
    "zaki", "zaki", "zege", "zenda", "zever",

    # Fulani Names
    "abdoulie", "abubacarr", "adama", "ahmadu", "aliu",
    "amadou", "amadu", "baba", "bah", "baldeh",
    "ballo", "bari", "barry", "bayo", "boubacar",
    "ceesay", "cham", "conteh", "dabo", "dan",
    "demba", "diallo", "drammeh", "faal", "faye",
    "fatty", "fofana", "foday", "gaye", "hamidou",
    "ibra", "jabbie", "jallow", "janneh", "jobe",
    "kah", "kamara", "keita", "kinteh", "kujabi",
    "kumba", "lamin", "mamadou", "manneh", "mbaye",
    "modou", "musa", "ndow", "ngom", "njie",
    "njoge", "njoku", "oumar", "ousmane", "saidou",
    "sallah", "sankareh", "sanyang", "seck", "secka",
    "sillah", "sissoko", "sonko", "sow", "suwareh",
    "tall", "thiam", "tijan", "toure", "traore",
    "usman", "wuri", "yahya", "yaya",

    # Kanuri Names (Borno)
    "abatcha", "abba", "abubakar", "aliyu", "baba",
    "babagana", "bintu", "borno", "bukar", "bulama",
    "dunoma", "gana", "goni", "grema", "gulumba",
    "gwoza", "idris", "isa", "kadai", "kaka",
    "kalli", "kolo", "konduga", "korau", "kukawa",
    "lawan", "madu", "maidugu", "maina", "mainok",
    "mallam", "modu", "mustapha", "sandabe", "shettima",
    "umar", "yusuf", "zulum",

    # Nupe Names
    "abdulmalik", "abubakar", "adamu", "agaie", "alfa",
    "aliyu", "bida", "dantsoho", "eba", "edozhigi",
    "etsu", "gbako", "gunu", "idris", "jibrin",
    "jiya", "katcha", "kolo", "kpotun", "kudu",
    "kure", "kwame", "lafiyagi", "lapai", "lemu",
    "makun", "masaba", "ndace", "ndagi", "ndanusa",
    "ndayako", "pategi", "saba", "sakiwa", "tsadu",
    "umaru", "usman", "wushishi", "yisa",
})