// Nigerian Government Mental Health Hospitals
// FNPH Yaba is pinned first per client requirement.
// Single source of truth — used by Home.jsx, Results.jsx, and pdfGenerator.js.
export const NIGERIAN_HOSPITALS = [

  // === FEDERAL & TEACHING HOSPITALS ===
  { name: "Federal Neuropsychiatric Hospital, Yaba", state: "Lagos", type: "Federal", address: "8 Harvey Road, Yaba, Lagos" },
  { name: "Lagos State University Teaching Hospital, Ikeja", state: "Lagos", type: "Teaching" },
  { name: "Lagos University Teaching Hospital, Idi-Araba", state: "Lagos", type: "Teaching" },
  { name: "State Psychiatric Hospital, Abia", state: "Abia", type: "State" },
  { name: "University of Uyo Teaching Hospital", state: "Akwa Ibom", type: "Teaching" },
  { name: "Psychiatric Hospital, Eket", state: "Akwa Ibom", type: "State" },
  { name: "Anambra State Psychiatric Hospital", state: "Anambra", type: "State", address: "Nawfia, Anambra" },
  { name: "Nnamdi Azikiwe University Teaching Hospital", state: "Anambra", type: "Teaching", address: "Nnewi Onitsha Old Road, Nnewi" },
  { name: "Chukwuemeka Odumegwu Ojukwu University Teaching Hospital", state: "Anambra", type: "Teaching", address: "Amaku, Awka" },
  { name: "Abubakar Tafawa Balewa University Teaching Hospital", state: "Bauchi", type: "Federal", address: "Hospital Road, Yandoka Rd, Bauchi" },
  { name: "Federal Medical Centre, Makurdi", state: "Benue", type: "Federal", address: "Hospital Road, Makurdi" },
  { name: "Federal Neuro-Psychiatric Hospital, Maiduguri", state: "Borno", type: "Federal" },
  { name: "Federal Neuro-Psychiatric Hospital, Calabar", state: "Cross River", type: "Federal" },
  { name: "University of Calabar Teaching Hospital", state: "Cross River", type: "Teaching" },
  { name: "Alex Ekwueme Federal University Teaching Hospital", state: "Ebonyi", type: "Federal", address: "Ntezi Abba, Abakaliki" },
  { name: "David Umahi Federal University Teaching Hospital", state: "Ebonyi", type: "Federal", address: "Uburu, Ohaozara" },
  { name: "Federal Neuro-Psychiatric Hospital, Uselu-Benin", state: "Edo", type: "Federal", address: "Uselu-Lagos Road, Benin City" },
  { name: "University of Benin Teaching Hospital (UBTH)", state: "Edo", type: "Teaching" },
  { name: "Federal Neuropsychiatric Hospital, New Haven", state: "Enugu", type: "Federal", address: "New Haven, Enugu" },
  { name: "University of Nigeria Teaching Hospital (UNTH)", state: "Enugu", type: "Teaching", address: "Ituku-Ozalla, Enugu" },
  { name: "Godfrey Okoye University Teaching Hospital", state: "Enugu", type: "Teaching", address: "Jideofor St, Enugu" },
  { name: "82 Division NA Medical Services and Hospital", state: "Enugu", type: "Federal", address: "Abakpa, Enugu" },
  { name: "ESUT Teaching Hospital Parklane", state: "Enugu", type: "State", address: "Enugu" },
  { name: "National Hospital", state: "FCT", type: "Teaching", address: "Central Business District, Abuja" },
  { name: "Karu General Hospital", state: "FCT", type: "Federal", address: "Old Karu, New Karu 900101" },
  { name: "Imo State University Teaching Hospital", state: "Imo", type: "Teaching", address: "Nkwerre, Orlu" },
  { name: "Federal Teaching Hospital, Owerri", state: "Imo", type: "Federal", address: "105 Hospital Road, Orlu Rd, Owerri" },
  { name: "Federal Neuro-Psychiatric Hospital, Kaduna", state: "Kaduna", type: "Federal", address: "Barnawa, Kaduna South LGA" },
  { name: "Kano State Psychiatric Hospital", state: "Kano", type: "State" },
  { name: "Aminu Kano Teaching Hospital", state: "Kano", type: "Teaching", address: "No 2 Zaria Road, Kano" },
  { name: "Federal Neuro-Psychiatric Hospital, Budo-Egba", state: "Kwara", type: "Federal" },
  { name: "University of Ilorin Teaching Hospital", state: "Kwara", type: "Teaching" },
  { name: "Federal Medical Centre, Bida", state: "Niger", type: "Federal", address: "4 Efu Etsu Yisa Street, Bida" },
  { name: "Federal Neuro-Psychiatric Hospital, Aro, Abeokuta", state: "Ogun", type: "Federal", address: "Aro, Abeokuta, Ogun" },
  { name: "Obafemi Awolowo University Teaching Hospital Complex (OAUTHC), Ile-Ife", state: "Osun", type: "Teaching" },
  { name: "University College Hospital (UCH), Ibadan", state: "Oyo", type: "Teaching" },
  { name: "Jos University Teaching Hospital (Drug unit at Vom Christian Hospital)", state: "Plateau", type: "Teaching", address: "Lamingo, Jos" },
  { name: "University of Port Harcourt Teaching Hospital", state: "Rivers", type: "Teaching", address: "East-West Road, Alakahia, Port Harcourt" },
  { name: "Federal Neuro-Psychiatric Hospital, Kware", state: "Sokoto", type: "Federal", address: "Maiduguri Rd, Bankanu, Sokoto" },
  { name: "State Psychiatric Hospital, Sokoto", state: "Sokoto", type: "State" },

  // === NIGERIA COUNSELLING AND REHABILITATION CENTRES (NCRC) — State Offices ===
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Abia", type: "Rehabilitation", address: "Old Party Secretariat, Ogbor Hill, Aba" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Adamawa", type: "Rehabilitation", address: "Old SDP Secretariat, No. 1 Abdullahi Bashir Street, Yola Road, Jimeta" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Akwa Ibom", type: "Rehabilitation", address: "291 Nwana-Iba Road, Uyo" },
  { name: "Martha Udom Rehabilitation Centre", state: "Akwa Ibom", type: "Rehabilitation", address: "Uyo, Akwa Ibom" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Anambra", type: "Rehabilitation", address: "Old Party Secretariat, Nsugbe Road, Onitsha" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Anambra", type: "Rehabilitation", address: "Road 1, House 1, Udoka Housing Estate, Awka" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Bauchi", type: "Rehabilitation", address: "White House, Mechanic Village, Jos Road, Bauchi" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Bayelsa", type: "Rehabilitation", address: "Okutukuta, Nbiama-Yenagoa Road, Bayelsa" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Bayelsa", type: "Rehabilitation", address: "Block 12, Road 2, Okaka Housing Estate, Yenagoa" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Benue", type: "Rehabilitation", address: "Old SDP Secretariat, Ankpa Road, Makurdi" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Borno", type: "Rehabilitation", address: "Old Party Secretariat, Gamboru Ngala Road, Maiduguri" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Cross River", type: "Rehabilitation", address: "3 Harbour Road, Calabar" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Delta", type: "Rehabilitation", address: "Old SDP Secretariat, Isah Road, Ogwashi-Uku" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Ebonyi", type: "Rehabilitation", address: "10 Elias Odili Street, Abakaliki" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Edo", type: "Rehabilitation", address: "Old SDP Secretariat, Upper Sokponba, Benin City" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Enugu", type: "Rehabilitation", address: "Old SDP Secretariat, Vosan Drive, Independence Layout, Enugu" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "FCT", type: "Rehabilitation", address: "Plot 1093, Joseph Gomwalk Street, Gudu, Abuja" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Gombe", type: "Rehabilitation", address: "Old BASAC Office, BCJ, Gombe" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Imo", type: "Rehabilitation", address: "Old NRC Party Office, Aba Road, Owerri" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Jigawa", type: "Rehabilitation", address: "NIFOR Quarters, Dutse" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Kaduna", type: "Rehabilitation", address: "Olusegun Obasanjo Secretariat, Yakubu Gowon Road, Kaduna" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Kano", type: "Rehabilitation", address: "Kano State Command, Airport Road, Kano" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Katsina", type: "Rehabilitation", address: "Party Secretariat, Kofar Kwaya, Katsina" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Kebbi", type: "Rehabilitation", address: "No. 25 Emir Haruna Road, Birnin Kebbi" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Kogi", type: "Rehabilitation", address: "New Layout, Liberty Hotel Area, Lokoja" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Kogi", type: "Rehabilitation", address: "No. 3, Tunde Ogbeha Street, GRA, Lokoja" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Kwara", type: "Rehabilitation", address: "Defunct NRC Party Office, KM 2 Sobi Barracks Road, Ilorin" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Lagos", type: "Rehabilitation", address: "5 Jogunomi Street, Gbagada Phase 2 Estate, Lagos" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Nasarawa", type: "Rehabilitation", address: "State Command, Makurdi Road, Lafia" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Niger", type: "Rehabilitation", address: "Defunct NRC Secretariat, Western Bye-Pass, Opposite Police Secondary School, Minna" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Ogun", type: "Rehabilitation", address: "Quarter 07, Oba Ademola Road, GRA, Abeokuta" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Ondo", type: "Rehabilitation", address: "257 Alagbaka, GRA, Akure" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Osun", type: "Rehabilitation", address: "Old Ikirun Road, Osogbo" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Oyo", type: "Rehabilitation", address: "QTR 585, Link Reservation, Onikere GRA, Ibadan" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Plateau", type: "Rehabilitation", address: "Former Signal Barracks, Katon-Rikkos, Jos" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Rivers", type: "Rehabilitation", address: "Defunct SDP Secretariat, Artillery Junction, Aba Road, Port Harcourt" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Sokoto", type: "Rehabilitation", address: "Former Party House, Kalam Baina Road, Arkilla Nasarawa" },
  { name: "Nigeria Counselling & Rehabilitation Centre", state: "Yobe", type: "Rehabilitation", address: "Plot No. 19, State Low-Cost Extension, Damaturu" },
]